### ISSUE TITLE
Metadata lookup

### ISSUE THREAD

**Issue by tirrolo** [IITDBGroup/gprom#54]
After compiling the code, when trying to execute gprom with postgres I get the following error:

FATAL(metadata_lookup.c:105) did not find plugin <METADATA_LOOKUP_PLUGIN_POSTGRES>
ERROR (exception.c:145) exception was thrown (RECOVERABLE) metadata_lookup.c - 105 - <did not find plugin <METADATA_LOOKUP_PLUGIN_POSTGRE\
S>>

Environment: Ubuntu 16.04

**Comment by lordpretzel** [comment]
there is a missing test in configure that does not fail if the postgres library is not found. This should be fixed by fixing the check. In the meanwhile this can be resolved by making suring that the development version of libpq is visible to configure and can be checked by looking at the compilation to see whether we compile against libpq.

**Comment by lordpretzel** [comment]
configure now fails if backend library headers are not available (including Postgres)
